name: CI/CD Pipeline for NextLife Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t devhuynh2003/fe-service .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push devhuynh2003/fe-service:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop and remove old container
        run: docker rm -f fe-service || true

      - name: Remove old images
        run: docker rmi -f devhuynh2003/fe-service:latest || true

      - name: Pull image from Docker Hub
        run: docker pull devhuynh2003/fe-service:latest

      - name: Run docker container
        run: |
          docker run -d \
            -p 3000:3000 \
            --env-file /home/ubuntu/.env \
            --health-cmd="curl -f http://localhost:3000/health || exit 1" \
            --health-interval=30s \
            --health-timeout=5s \
            --health-retries=3 \
            --health-start-period=10s \
            --name fe-service \
            devhuynh2003/fe-service:latest

