name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: Build docker image
        run: docker build -t devhuynh2003/nextjs-app .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push devhuynh2003/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Xóa container cũ trên server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            CONTAINER_NAME="nextjs-app-container"

            # Kiểm tra xem container có tồn tại không
            if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
              echo "Container '$CONTAINER_NAME' found. Stopping..."

              # Dừng container nếu đang chạy
              docker stop $CONTAINER_NAME || true
              
              echo "Removing container '$CONTAINER_NAME'..."

              # Xóa container
              docker rm -f $CONTAINER_NAME || true
            else
              echo "Container '$CONTAINER_NAME' does not exist. No action taken."
            fi

      - name: Pull image from Docker Hub
        run: docker pull devhuynh2003/nextjs-app:latest

      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container devhuynh2003/nextjs-app:latest
